### ISSUE TITLE
Orden de variables

### ISSUE THREAD

**Issue by financieras** [RebecaGa/TFG---URJC-2020-2021#10]
Estamos en 6. Rentas

Donde dice:

```
n = 120
pmt = 1000
i = 0.07
im = (1+i)**(1/m)-1
m = 12
```

debe decir:

```
n = 120
pmt = 1000
i = 0.07
m = 12
im = (1+i)**(1/m)-1
```
Es necesario definir previamente el valor de m antes de usarle en la fórmula ya que en caso contrario da error.

**Comment by RebecaGa** [comment]
Si, gracias. A veces como estás cambiando el código, este tipo de detalles se pierden a no ser que cierres el archivo y vuelvas a entrar. Ya está corregido.
