### ISSUE TITLE
Tanto semestral

### ISSUE THREAD

**Issue by financieras** [RebecaGa/TFG---URJC-2020-2021#11]
Estamos en 9. Ejemplos prácticos VAN & TIR.ipynb

Veamos el siguiente códgio:

```
#Fórmula VNA

cf = [-70000, 12000, 12000, 12000, 12000, 12000, 12000, 12000, 12000]
i = 0.10
n = 6
ises = (1+i)**(1/n)-1

VAN = npf.npv(rate = ises, values = cf)
print(VAN)

#Fórmula VA

pago = 70000
pmt = 12000
m = 8

VA = npf.pv(rate = ises, nper = m, pmt=-pmt, fv=0, when='end')-pago #tenemos que sacar fuera el pago inicial
print(VA)
```
Existe un error al calcular el interés semestral efectivo (ises) se usa el valor de n igual a 6 cuando debe ser 2, ya que el año tiene dos semestres.
A esa variable prefiero llamarla m (frecuencia) que es el número de subperiodos que hay en el año. Si el subperiodo es el semestre en el año hay dos subperiodos, por lo que m=2.

Te propongo el siguiente códgio.

```
#Fórmula VNA

cf = [-70000, 12000, 12000, 12000, 12000, 12000, 12000, 12000, 12000]
i = 0.10
m = 2
i2 = (1+i)**(1/m)-1 # i2 es el tanto semestral efectivo

VAN = npf.npv(rate = i2, values = cf)
print(VAN)

#Fórmula VA

pago = 70000
pmt = 12000
n = 8

VA = npf.pv(rate = i2, nper = n, pmt=-pmt, fv=0, when='end')-pago #tenemos que sacar fuera el pago inicial
print(VA)
```
Con el nuevo código el resultado es 7933.380487871074

**Comment by RebecaGa** [comment]
Toda la razón, error importante confundir semestres con 6. Corregido.

Tiene razón también con el término 'frecuencia'. A veces cuando hago los ejercicios quiero plantearlos para alguien que no sepa nada de finanzas, pero al final me lleva a utilizar términos poco apropiados. Debo cambiar el chip en este sentido. Procuraré tenerlo en mente... gracias por esta indicación.
