### ISSUE TITLE
Eje X del gráfico

### ISSUE THREAD

**Issue by financieras** [RebecaGa/TFG---URJC-2020-2021#5]
Estamos en 1. Operaciones Simples.ipynb

Falta el último valor del eje X en el gráfico. Se puede conseguir sustituyendo esta línea:

`plt.xticks(np.arange(tiempo[0], tiempo[-1], 1))`

por esta otra:

`plt.xticks(np.arange(tiempo[0], tiempo[-1]+1, 1))`

**Comment by RebecaGa** [comment]
Perfecto. Gracias!
