### ISSUE TITLE
Misma unidad temporal

### ISSUE THREAD

**Issue by financieras** [RebecaGa/TFG---URJC-2020-2021#7]
Estamos en: 5. Ejemplos Prácticos. Cómo usar librería Numpy Financial

Donde dice:

`por lo que tenemos que dividir los meses entre 12 para pasar el tiempo a anualidades, ya que todas las cantidades deben ser proporcionales,  es decir, si el interés es en años, el tiempo debe ser años, y las cantidades reflejan años`

podría decir:

`por lo que tenemos que dividir los meses entre 12 para pasar el tiempo a años, ya que todas las cantidades deben ser proporcionadas con la misma unidad temporal, es decir, si el tanto es anual la duración de la operación debe expresarse en años.`

**Comment by RebecaGa** [comment]
Hecho.
