### ISSUE TITLE
Separador de miles a dos decimales

### ISSUE THREAD

**Issue by financieras** [RebecaGa/TFG---URJC-2020-2021#8]
Estamos en 

Donde dice:

`print("La deuda de Andrés es {} euros".format(round(fv,2)))`

podría decir:

`print("La deuda de Andrés es {:,.2f} euros.".format(fv))`

con esto se consigue que aparezca el importe con separador de miles.
Quedaría así:

La deuda de Andrés es 138,534.76 euros.

Esta idea se podría aplicar a todas los importes en euros que se desan imprimir.
Puede ser mejor que redondear a dos decimales, si esto es lo que se desea ya que si redondeamos los importes que se obtienen ya no son exactos en caso de que se utilicen para un cálculo posterior.

**Comment by RebecaGa** [comment]
me parece bien, funciona y queda mejor. De momento he cambiado este punto, pero después revisaré todo y lo cambiaré siempre que me refiera a euros.
